var config = {
	platform:				"Common",
	loginSuccessURL:		"http://but4ataxuwr3.trekea.com/FieldLogsUser/resources/english/main/index.html",
	loginURL:				"http://but4ataxuwr3.livetrekker.com/MainWebApp/actions/login/Login",
	createNewBuyerURL: 		"http://but4ataxuwr3.livetrekker.com/MainWebApp/api/latest/user/SecureCreateNewBuyer",
	sendActivationEmail: 	"http://but4ataxuwr3.livetrekker.com/MainWebApp/api/latest/user/SendActivationEmail",
	forgotMyPassword:		"http://but4ataxuwr3.livetrekker.com/MainWebApp/actions/user/ForgotMyPassword",
	openSession:		"http://but4ataxuwr3.livetrekker.com/MainWebApp/actions/OpenSession",
	activateUserCreationInvitation:		"http://but4ataxuwr3.livetrekker.com/MainWebApp/api/latest/user/ActivateUserCreationInvitation",
	applicationId:			"f803ef3045104e990050fc6b9425c044",
	customerId:				"FieldLogs",
	recaptchaKey:			"6LewB88SAAAAAKf6zcfm1ZDRQFWsVK6otFWV75iF",
	operation:				"redirect",
	cookieParam:			"fieldlogs.params",
	cookiePath:				"/",
	cookieDomain:			"but4ataxuwr3.fieldlogs.com",
	staticSiteRoot:			"http://but4ataxuwr3.trekea.com/FieldLogsStatic/",
	appStoreLink:			"https://itunes.apple.com/en/app/fieldlogs/id640497763",
	googleAppStoreLink:		"https://play.google.com/store/apps/details?id=com.trekea.fieldlogs"
};
